---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  labels:
    secrets.stackable.tech/class: airflow-progdtd-credentials-class
stringData:
  accessKey: minioAccessKey
  secretKey: alcpemFXsSfsdff122
  # The following two entries are used by the Bitnami chart for MinIO to
  # set up credentials for accessing buckets managed by the MinIO tenant.
  root-user: minioAccessKey
  root-password: BB5gkfdlk6TH78
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: airflow-progdtd-credentials-class
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}